swagger: "2.0"
info:
  title: "Localhost(ssh) API"
  description: "A simple service to execute commands on the specified host. This API requires Basic Authentication"
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST service"
  license: 
    name: "Apache"
securityDefinitions:
  basicAuth:
    type: "basic"
# To apply Basic auth to the whole API:
security:
  - basicAuth: []
host: "localhost:8080"
basePath: "/cloudmesh/localhost/hid-sp18-516"
schemes:
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths:
  /{command}:
    post:
      # To apply Basic auth to an individual operation:
      security:
        - basicAuth: []
      description: "Executes command on the specified host"
      operation_id: app.post_command
      parameters:
        - in: body
          name: entities
          description: "The username and hostname to execute the command on"
          schema:
            $ref: '#/definitions/ENTITIES'
        - in: path
          name: command
          description: "The command to execute on the specified host"
          required: true
          type: string
          schema:
            $ref: '#/definitions/COMMAND'
      responses:
        200:
          description: "command was executed successfully."
        400:
          description: "Bad request."
        401:
          description: "Authorization information is missing or invalid."
        404:
          description: "Not Found."
definitions:
  COMMAND:
    type: "object"
    required: 
      - "command"
    properties: 
      command:
        type: "string"
  ENTITIES:
    type: "object"
    required:
      - "userName"
      - "hostName"
    properties:
      userName:
        type: "string"
      hostName:
        type: "string"
